language: ruby
rvm:
- 2.0.0
deploy:
  provider: rubygems
  api_key:
    secure: gzvD+LH/hVa7RmW3C9Vf6v+asnClSj3I5EHpghwnG7oxJNCiKW1N3zTHPE64M+GhOus9kXlL2/oy358kSNyKAv2eEiqifMs5+hrFAqIU8jEPG+jvaVhBsVpmKedEZEc4ZDgn0Y71Et3+U8+VAEK7iAOQmgKSlVWF1qJxMV7lXSw=
  gem: vagrant-winrm
  on:
    tags: true
    repo: criteo/vagrant-winrm
